# Generated by Django 3.1 on 2020-08-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subeer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serial",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
    ]
