# Generated by Django 3.0.8 on 2020-08-28 21:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("subeer", "0005_auto_20200822_1611"),
    ]

    operations = [
        migrations.AddField(
            model_name="serial",
            name="poster",
            field=models.ImageField(
                blank=True, upload_to="static/img/serial", verbose_name="Постер"
            ),
        ),
        migrations.AlterField(
            model_name="episode",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 8, 28, 21, 14, 54, 248644, tzinfo=utc)
            ),
        ),
        migrations.AlterField(
            model_name="episode",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 8, 28, 21, 14, 54, 248671, tzinfo=utc)
            ),
        ),
        migrations.AlterField(
            model_name="serial",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 8, 28, 21, 14, 54, 247387, tzinfo=utc)
            ),
        ),
        migrations.AlterField(
            model_name="serial",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 8, 28, 21, 14, 54, 247420, tzinfo=utc)
            ),
        ),
    ]
