# Generated by Django 3.1 on 2020-09-04 18:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('subeer', '0006_auto_20200828_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='Description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='opinion',
            name='Login',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='opinion',
            name='date_opinion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 4, 18, 14, 37, 606701, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='episode',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 4, 18, 14, 37, 606728, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='serial',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 4, 18, 14, 37, 605444, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='serial',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 4, 18, 14, 37, 605477, tzinfo=utc)),
        ),
    ]
