# Generated by Django 3.1.1 on 2020-12-17 00:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("subeer", "0009_auto_20201204_1604"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 12, 17, 0, 56, 12, 520307, tzinfo=utc)
            ),
        ),
        migrations.AlterField(
            model_name="episode",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 12, 17, 0, 56, 12, 520334, tzinfo=utc)
            ),
        ),
        migrations.AlterField(
            model_name="serial",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 12, 17, 0, 56, 12, 519193, tzinfo=utc)
            ),
        ),
        migrations.AlterField(
            model_name="serial",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 12, 17, 0, 56, 12, 519223, tzinfo=utc)
            ),
        ),
    ]
