# Generated by Django 3.1.1 on 2021-01-01 15:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('subeer', '0013_auto_20210101_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='total_likes',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='episode',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 1, 15, 0, 13, 839424, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='episode',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 1, 15, 0, 13, 839448, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='serial',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 1, 15, 0, 13, 837780, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='serial',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 1, 15, 0, 13, 837810, tzinfo=utc)),
        ),
    ]
