# Generated by Django 3.1.1 on 2021-01-01 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("subeer", "0014_auto_20210101_1500"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="episode",
            name="updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="serial",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="serial",
            name="updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
